name: Meu Primeiro Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Listar ficheiros no repositório
        run: ls -la

      - name: Pipeline concluído
        run: echo "Pipeline executado com sucesso!"
